services:
  backstage:
    build: .
    image: ${DOCKER_REGISTRY_URL}/backstage:${IMAGE_TAG}
    ports:
      - "7015:7015"
    env_file:
      - .env
      - ../../env/backstage/.env
    restart: always
    networks:
      - cuvera-network
    volumes:
      - type: volume
        source: backstage-temp-data
        target: /data

    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        # reservations:
        #   memory: 512M
        #   cpus: '0.25'

    security_opt:
      - no-new-privileges:true

    stop_grace_period: 30s
    stop_signal: SIGTERM

volumes:
  backstage-temp-data:
    driver: local

networks:
  cuvera-network:
    external: true